services:
  seacor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SEACOR_LOG_LEVEL=${SEACOR_LOG_LEVEL}
      - MONICA_API_KEY=${MONICA_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
