# SEACOR設定ファイル

# LLM設定
llm:
  provider: monica  # monica, openai, anthropic など
  model: claude-3-5-haiku-latest
  temperature: 0.7
  max_tokens: 2000
  timeout: 30

# ログ設定
log_level: INFO
log_file: logs/seacor.log

# 専門家設定
default_expertise:
  - プログラミング
  - システム設計
  - データ分析
  - プロジェクト管理
  - 問題解決
max_experts: 10

# ツール設定
enabled_tools: []
#  - web_search
#  - code_analysis
#  - growth_tracker
#  - knowledge_base

# キャッシュ設定
cache_dir: .cache
cache_ttl: 3600  # キャッシュの有効期限（秒）

# リトライ設定
max_retries: 3
retry_delay: 1  # リトライ間隔（秒）

# タイムアウト設定
timeout: 30  # デフォルトのタイムアウト（秒）

# 成長設定
growth:
  min_confidence: 0.7  # 成長判定の最小信頼度
  max_iterations: 5    # 最大反復回数
  learning_rate: 0.1   # 学習率

# 知識ベース設定
knowledge_base:
  path: data/knowledge
  max_size: 1000  # 最大エントリ数
  update_interval: 3600  # 更新間隔（秒）

# セキュリティ設定
security:
  api_key_required: true
  rate_limit: 100  # 1分あたりのリクエスト制限
  allowed_origins:  # CORS設定
    - http://localhost:8000
    - https://seacor.example.com 