tools:
  code_analysis:
    name: code_analysis
    description: コードの分析と最適化を行うツール
    type: CodeAnalysisTool
    config:
      max_tokens: 4000
      temperature: 0.1
      model: gpt-4o-mini

  web_search:
    name: web_search
    description: ウェブ検索を行うツール
    type: WebSearchTool
    config:
      max_tokens: 2000
      temperature: 0.3
      model: gpt-4o-mini
      search_engine: google
      max_results: 5

  # 必要に応じて他のツールを追加
  # documentation:
  #   name: documentation
  #   description: ドキュメント生成ツール
  #   type: DocumentationTool
  #   config:
  #     max_tokens: 3000
  #     temperature: 0.2
  #     model: gpt-4-turbo-preview 