version: "0.1.0"

llm:
  provider: monica_llm
  model: gpt-4o-mini
  temperature: 0.7

logging:
  level: INFO

growth:
  min_confidence: 0.7
  max_iterations: 5
  learning_rate: 0.1

# dependencies: loaded by ConfigLoader