scrape_website:
  type: tool
  provider: crewai_tools
  class: ScrapeWebsiteTool
  description: ウェブサイトの内容をスクレイピングして取得するツール

# spider:
#   type: tool
#   provider: crewai_tools
#   class: SpiderTool
#   description: 指定したURLからリンクをたどってクロール・情報収集するツール

brave_search:
  type: tool
  provider: crewai_tools
  class: BraveSearchTool
  description: Brave Search APIを利用してウェブ検索を行うツール 