flow_review_task:
  name: flow_review_task
  description: >
    クルーやフロー全体の構成・プロセスをレビューし、以下を明確にしてください。
    1. 現状の問題点や非効率な箇所の指摘
    2. 具体的な改善案・最適化案（期待される効果や根拠も記載）
    3. 出力は分かりやすい構造化リストで
    ユーザーの質問は以下のとおり。
    {prompt}
    生成したアウトプットは以下の通り。
    {system_message}
  agent: flow_reviewer_agent
  expected_output: >
    problems, suggestions などを含む構造化JSON。
    各項目に説明・根拠・期待効果を明記すること。
  config: {}

flow_review_feedback_task:
  description: >
    入力と出力を比較し、出力内容の正確性・妥当性を評価してください。
    必要に応じて具体的な修正案や改善点も提案すること。
  expected_output: >
    出力の正しさ評価・修正案（理由や根拠も明記）
  human_input: false
  config: {}

flow_review_revise_task:
  description: >
    フィードバックtaskの評価・修正案をもとに、最終的に最適化された回答や出力を作成してください。
    変更点や改善理由も明記すること。
  expected_output: >
    明確で実用的かつフィードバックを反映した最終回答・出力（改善理由付き）
  human_input: false
  config: {}