main_task:
  description: >
    ユーザーの質問や指示に対し、利用可能なツール・知識・情報源を最大限活用し、
    論理的根拠とともに最適な回答を生成してください。
    回答は明確・簡潔・実用的であること。
    ユーザーの質問は以下のとおり。
    {prompt}
  expected_output: >
    ユーザーにとって最適かつ根拠が明示された回答（必要に応じて箇条書きや構造化形式）
    なお、outputはinputと同一の言語で出力してください。
  human_input: false
  config: {}

main_feedback_task:
  description: >
    入力と出力を比較し、出力内容の正確性・妥当性を評価してください。
    必要に応じて具体的な修正案や改善点も提案すること。
  expected_output: >
    出力の正しさ評価・修正案（理由や根拠も明記）
  human_input: false
#  async_execution: true
  config: {}
  context:
    - main_task

main_revise_task:
  description: >
    フィードバックtaskの評価・修正案をもとに、最終的に最適化された回答や出力を作成してください。
    ユーザーの質問は以下のとおり。
    {prompt}
  expected_output: >
    明確で実用的かつフィードバックを反映した最終回答・出力。
    なお、outputはinputと同一の言語で出力してください。
  human_input: false
#  async_execution: true
  config: {}
#  context:
#    - main_task
#    - main_feedback_task
