feedback_task:
  description: >
    入力と出力を比較し、出力内容の正確性・妥当性を評価してください。
    必要に応じて具体的な修正案や改善点も提案すること。
  expected_output: >
    出力の正しさ評価・修正案（理由や根拠も明記）
  human_input: false
  config: {}

revise_task:
  description: >
    フィードバックtaskの評価・修正案をもとに、最終的に最適化された回答や出力を作成してください。
    変更点や改善理由も明記すること。
  expected_output: >
    明確で実用的かつフィードバックを反映した最終回答・出力（改善理由付き）
  human_input: false
  config: {}