evolution_crew:
  name: evolution_crew
  description: クルーやエージェントの進化・拡張案を生成する。
  agents:
    - evolution_agent
    - feedback_agent
    - evolution_manager_agent
  tasks:
    - evolution_task
    - evolution_feedback_task
    - evolution_revise_task
  process: hierarchical
  manager_agent: evolution_manager_agent
  planning: true
  planning_llm: monica_llm
  output_log_file: logs/evolution_crew.json
  memory: false
  callback: []
#    - core/evolution_callback.py
  verbose: true 
  config: {} 