main_crew:
  name: main_crew
  description: メインの業務遂行クルー。入力されたプロンプトに対して回答を作成する。
  agents:
    - main_agent
    - feedback_agent
    - web_scraper_agent
    - search_agent
  tasks:
    - main_task
    - main_feedback_task
    - main_revise_task
  process: hierarchical
  manager_llm: monica_llm
  manager_agent: main_manager_agent
  planning: true
  planning_llm: monica_llm
  output_log_file: logs/main_crew.json
  memory: true
  memory_config: {"provider": "basic"}
  kickoff_async: true
  callback: []
  verbose: true
  config: {}
